export const SITE = {
  website: import.meta.env.PUBLIC_SITE_URL ?? "http://localhost:4321",
  author: "Daniel Borkeby",
  profile: "https://solopreneur.se",
  desc: "Solopreneur.se – guider, verktyg och kunskap för soloföretagare.",
  title: "Solopreneur.se",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "sv",
  timezone: "Europe/Stockholm",
} as const;